CREATE USER aspsp WITH PASSWORD 'password';
CREATE DATABASE aspsp WITH OWNER aspsp;
GRANT ALL PRIVILEGES ON DATABASE aspsp TO aspsp;

CREATE USER tpp WITH PASSWORD 'password';
CREATE DATABASE tpp WITH OWNER tpp;
GRANT ALL PRIVILEGES ON DATABASE tpp TO tpp;

CREATE USER idp WITH PASSWORD 'password';
CREATE DATABASE idp WITH OWNER idp;
GRANT ALL PRIVILEGES ON DATABASE idp TO idp;
