---
- name: "all"
  hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: Include Project Vars
      include_vars:
        dir: "{{base_dir}}/conf.d/project.d"
        extensions: ['yaml', 'yml']
        name: project
      tags: always

    - name: Include DNS Vars
      include_vars:
        dir: "{{base_dir}}/conf.d/dns.d"
        extensions:  ['yaml', 'yml']
        name: dns
      tags: always

    - name: Include Player Vars
      include_vars:
        dir: "{{base_dir}}/conf.d/players.d"
        extensions: ['yaml', 'yml']
        ignore_files: ['README.md']
        name: players
      tags: always

    - name: Set Build Folder
      set_fact:
        out_dir: "{{ project.rootDir }}/{{ project.buildDir }}"
      tags: always

    - name: Include Docker Vars
      include_vars:
        dir: "{{base_dir}}/conf.d/docker.d"
        extensions: ['yaml', 'yml']
        name: docker
      tags: always

    - name: Include SSL Vars
      include_vars:
        dir: "{{base_dir}}/conf.d/ssl.d"
        extensions: ['yaml', 'yml']
        name: ssl
      tags: always

    - name: Set SSL Build Folder
      set_fact:
        ssl_out_dir: "{{ project.rootDir }}/{{ project.buildDir }}/{{project.sslDir}}"
      tags: always

    # Load he service descriptions.
    - name: Include Service Descriptions
      include_vars:
        dir: "{{base_dir}}/conf.d/services.d"
        name: services
        extensions: ['yaml', 'yml']
      tags: always

  roles:
    - ssl
    - docker
